export enum MuscleEnum {
  CHEST = "chest",
  FULL_BODY = "full_body",
  CARDIO = "Cardio",
  UPPER_BACK = "upper_back",
  LOWER_BACK = "lower_back",
  LATS = "lats",
  SHOULDERS = "shoulders",
  BICEPS = "biceps",
  TRICEPS = "triceps",
  FOREARMS = "forearms",
  ABS = "abs",
  GLUTES = "glutes",
  QUADRICEPS = "quadriceps",
  HAMSTRINGS = "hamstrings",
  CALVES = "calves",
  ADDUCTORS = "adductors",
  ABDUCTORS = "abductors",
  TRAPEZIUS = "trapezius",
}
